Configuratron:
  use_only:
    # - tuep
    - bci_iv_2a
    # - erpbci
    # - mmidb
    # - sleep-edf
    # - ern
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False
  load_onthefly: True
  

encoder_weights: trained_weights/encoder.pt
context_weights: trained_weights/contextualizer.pt

datasets: !include configs/downstream_datasets.yml

