Configuratron:
  use_only:
    - bci_iv_2a
    - sleep-edf
    - mmidb
    - erpbci
    - ern 
  preload: False
  sfreq: 256
  deep1010:
    return_mask: False
  

encoder_weights: trained_weights/encoder.pt
context_weights: trained_weights/contextualizer.pt

datasets: !include configs/downstream_datasets.yml

